title: The International Customers Team Homepage
author: Simone V. DIVAKOVA
email: divakova.sv@pg.com
description: > # this means to ignore newlines until "baseurl:"
  This is the homepage for the P&G International Customers Team.
  Here you can redirect yourself to the relevant folders and files.

# social links
twitter_username: your-twitter-handle
github_username:  SimoneDivakova

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
